### ISSUE TITLE
[Bug]: [1.19.2]

### ISSUE THREAD

**Issue by MokahTGS** [TheIllusiveC4/CustomFoV#12]
### Minecraft Version

1.19.2

### What happened?

Client crash on load.

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge 43.2.0

### Mod Version

customfov-forge-6.0.0-beta.1+1.19.2.jar

### Relevant Log Outputs

Crash log: https://pastebin.com/ciqdvyHv

**Comment by TheIllusiveC4** [comment]
Do you have Optifine installed?

**Comment by MokahTGS** [comment]
No.

My mod list: https://pastebin.com/RT5kfpy6

**Comment by TheIllusiveC4** [comment]
After reproducing your instance, I have not encountered a crash of any sort and I have not gotten additional reports about this. I can only assume that perhaps something else in your environment is causing the issue or another mod was causing this and has since been updated.

If you are still having trouble with this issue, I recommend the following:

1) Test to see if the mod works by itself. This will isolate any other mod conflicts.
2) If the above works, then isolate which mod may be producing the conflict by removing half of the mods at a time until a candidate is found.

**Comment by The-Arcanian** [comment]
After trying to track down this same crash for a few hours it seems that Custom FoV always gets the blame in the crash log if any mod is missing a required dependency. If it occurs outside of that it is an inconsistent bug that will not show every run.

**Comment by TheIllusiveC4** [comment]
Are you saying that this is a false positive that only occurs when another mod is missing a required dependency?

Or is this a legitimate crash that happens rarely in addition to that false positive?

**Comment by The-Arcanian** [comment]
It is at least a false positive that occurs when another mod is missing a required dependency.

I cannot say for certain if it is also sometimes a legitimate crash or not, due to it being rare if that is the case. But it has yet to happen again while I have been updating my personal mod pack from 1.18.2 to 1.19.2, and I have been relaunching every 5 mods added.
