### ISSUE TITLE
[Bug]: Crash when booting right before getting to Main Menu.

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/CustomFoV#15]
### Minecraft Version

1.20.1

### What happened?

Can't open the client, crashes when getting to main menu.
"Exception caught during firing event"

### How do you trigger this bug?

1. Install mod
2. Start client-
3. Wait.
4 Crash.
.. Profit.

### Loader

Forge

### Loader Version

47.0.3

### API Version

N/A

### Mod Version

customfov-forge-6.2.0+1.20.1.jar

### Relevant Log Outputs

https://gist.github.com/Gbergz/8e88142b2a75d634cd6a2accc3f7b183

**Comment by TheIllusiveC4** [comment]
That's odd, I can't reproduce this. Was this your first time starting the mod? Do you have a `customfov.txt` file in your instance's folder somewhere? If so, can you share its contents?

Edit: If there is no `customfov.txt` file, can you share your full log output from the crash?

**Comment by Gbergz** [comment]
[customfov.txt](https://github.com/illusivesoulworks/customfov/files/11793771/customfov.txt)

Here's the customfov.txt file

Edit: Gonna guess the issue is mod conflict, since I do have other mods present in my instance.

**Comment by Gbergz** [comment]
Here's full logs: https://gist.githubusercontent.com/Gbergz/75cb5debc5f599d78160b7501884d2fc/raw/638f5490d8d0c182ae0f46cc0e17a7dfcc1af702/gistfile1.txt
And crash-report: https://gist.githubusercontent.com/Gbergz/b43f2116725f69faf787316d6791dba0/raw/d31e552d01adf38ef00c969a4a94970b3980c315/gistfile1.txt

**Comment by TheIllusiveC4** [comment]
Very strange, I'm not sure how your `customfov.txt` file could've ended up like that. Okay, can you try two things for me:

1) Delete `customfov.txt` and then try booting it up again. Does it still crash? If it doesn't, boot it up a second time to confirm.
2) Start a new instance with just Custom FOV and see if it crashes.

**Comment by Gbergz** [comment]
1. Did that, nothing new, same crash. Logs etc.
![bild](https://github.com/illusivesoulworks/customfov/assets/26634554/02cc030b-3c69-4e3f-836f-bdcaa3ad0da8)

2. This does work, no crashes. So as I put it earlier I think it's a mod conflict of some kind.

**Comment by TheIllusiveC4** [comment]
I have no idea what could be causing this. It seems like something is somehow either nullifying the vanilla options or delaying their load somehow.

I'll see if I can make a suitable workaround for this.

In the meantime, if you are able, it would be very helpful if you could isolate the mod causing this in order to solidify a long-term solution.

**Comment by Gbergz** [comment]
I will go through every mod till it boots.
I'll post an update when I am done.

**Comment by TheIllusiveC4** [comment]
You don't need to go through every mod one by one, you can trim the mod list by half and work your way down instead so that it takes less steps and you can isolate half of the mods each time.

Also, I should clarify, the issue is that the `customfov.txt` file got malformed somehow. It will always crash if the game is started with that file intact. To find the culprit, you would need to delete the file each time to make sure it tries to generate a new one.

**Comment by Gbergz** [comment]
Yep the first you wrote there is what I was planning. Kinda wrote it wrong.

And for the second part. Glad you reminded me.

**Comment by Gbergz** [comment]
Alright, I've found the mod causing this specific issue and it's [Default Options](https://www.curseforge.com/minecraft/mc-mods/default-options).

Removing the customfov.txt file then removing that mod, allows the game to boot.

**Comment by TheIllusiveC4** [comment]
Alright, thank you very much. I'm able to reproduce the crash on my end now and I'll begin working on a solution to make the two mods work together.

**Comment by TheIllusiveC4** [comment]
This should be fixed now in the new version, but let me know if it persists.

**Comment by Gbergz** [comment]
All fixed! Thanks :)
