### ISSUE TITLE
[Bug]: Game crash

### ISSUE THREAD

**Issue by TomSipsOnCurry** [TheIllusiveC4/CustomFoV#8]
### Minecraft Version

1.19.2

### What happened?

When I use custom FOV my game crashes and it gives me an exit code of 1. Attached is the mods I use.
![image](https://user-images.githubusercontent.com/78724847/194478588-c4d9bf81-70be-43e4-a691-aa26f1811c10.png)

### How do you trigger this bug?

1. Launch MC 1.19.2 Fabric with Custom FOV
2. Game will loadup
3.Then game will crash

### Loader

Fabric

### Loader Version

fabric loader-1.14.9-19.2

### Mod Version

customfov-fabric-6.0.0-beta.1+1.19.2

### Relevant Log Outputs
(https://hastebin.com/oforefujeh.yaml)

**Comment by TheIllusiveC4** [comment]
This crash is caused by Optifine removing a field that Custom FoV uses. Unfortunately, this means that the two mods are incompatible.

**Comment by TomSipsOnCurry** [comment]
Is there any alternative? As my game lags constantly when near a beacon. And I dont want to disable dynamic fov.

**Comment by TheIllusiveC4** [comment]
https://lambdaurora.dev/optifine_alternatives/

**Comment by TomSipsOnCurry** [comment]
:( I don't want to not use optifabric. Is there any alternative to CustomFov? Or a workaround?

**Comment by TheIllusiveC4** [comment]
If there is an alternative to Custom FoV, I don't know of it. And there is no workaround currently. Like I said, Optifine is removing a field that Custom FoV uses. This means that this is something that needs to be fixed on Optifine's end. But Optifine isn't really designed with mod compatibility in mind, which is why it's generally suggested to use alternatives designed for Forge/Fabric ecosystems instead of Optifine.

Edit: For example, Sodium is an alternative to Optifine that people have reported to me works perfectly fine with Custom FoV.
